bid_index:
    path:     /
    defaults: { _controller: "CACommerceBundle:Bid:index" }
    methods:  GET

bid_show:
    path:     /{id}/show
    defaults: { _controller: "CACommerceBundle:Bid:show" }
    methods:  GET

bid_new:
    path:     /new
    defaults: { _controller: "CACommerceBundle:Bid:new" }
    methods:  [GET, POST]

bid_edit:
    path:     /{id}/edit
    defaults: { _controller: "CACommerceBundle:Bid:edit" }
    methods:  [GET, POST]

bid_delete:
    path:     /{id}/delete
    defaults: { _controller: "CACommerceBundle:Bid:delete" }
    methods:  DELETE
