product_index:
    path:     /
    defaults: { _controller: "CACommerceBundle:Product:index" }
    methods:  GET

product_show:
    path:     /{id}/show
    defaults: { _controller: "CACommerceBundle:Product:show" }
    methods:  [GET, POST]

product_show_comments:
    path:     /{id}/show/rates
    defaults: { _controller: "CACommerceBundle:Rate:show" }
    methods:  [GET]

product_show_bids:
    path:     /{id}/show/bids
    defaults: { _controller: "CACommerceBundle:Bid:show" }
    methods:  [GET]

product_new:
    path:     /new
    defaults: { _controller: "CACommerceBundle:Product:new" }
    methods:  [GET, POST]

product_edit:
    path:     /{id}/edit
    defaults: { _controller: "CACommerceBundle:Product:edit" }
    methods:  [GET, POST]

product_delete:
    path:     /{id}/delete
    defaults: { _controller: "CACommerceBundle:Product:delete" }
    methods:  DELETE
