product_index:
    path:     /
    defaults: { _controller: "CACommerceBundle:Product:index" }
    methods:  GET

product_show:
    path:     /{id}/show
    defaults: { _controller: "CACommerceBundle:Product:show" }
    methods:  [GET, POST]

# product_show:
#     path:     /{id}/show
#     defaults: { _controller: "CACommerceBundle:Bid:new" }
#     methods:  [PUT]

product_new:
    path:     /new
    defaults: { _controller: "CACommerceBundle:Product:new" }
    methods:  [GET, POST]

product_edit:
    path:     /{id}/edit
    defaults: { _controller: "CACommerceBundle:Product:edit" }
    methods:  [GET, POST]

product_delete:
    path:     /{id}/delete
    defaults: { _controller: "CACommerceBundle:Product:delete" }
    methods:  DELETE
