rate_index:
    path:     /
    defaults: { _controller: "CACommerceBundle:Rate:index" }
    methods:  GET

rate_new:
    path:     /new
    defaults: { _controller: "CACommerceBundle:Rate:new" }
    methods:  [GET, POST]

rate_edit:
    path:     /{id}/edit
    defaults: { _controller: "CACommerceBundle:Rate:edit" }
    methods:  [GET, POST]

rate_delete:
    path:     /{id}/delete
    defaults: { _controller: "CACommerceBundle:Rate:delete" }
    methods:  DELETE
